# Generated by Django 3.0.8 on 2020-07-26 08:01
import requests
from bs4 import BeautifulSoup
from django.db import migrations

from apps.ingredient.models import Ingredient


def fill_calories_and_names(apps, schema_editor):
    url = 'http://www.takzdorovo.ru/db/nutritives/'
    html = requests.get(url)
    d = {}
    soup = BeautifulSoup(html.text, 'html.parser')

    for table in soup.find_all('table', class_='energy-res-tb'):
        for tr in table.find_all('tr'):
            name = tr.th.text
            ccal = float(tr.find_all('td')[3].find('a').text)
            d[name] = ccal

    Ingredient = apps.get_model('ingredient', 'Ingredient')

    for key, item in d.items():
        Ingredient.objects.create(name=key, calorie=item)


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_calories_and_names),
    ]
