# Generated by Django 3.0.8 on 2020-07-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('sum_of_calories', models.FloatField(default=0.0, verbose_name='Сумма калорий')),
                ('price', models.IntegerField(default=0.0, verbose_name='Стоимость')),
                ('ingredients', models.ManyToManyField(to='ingredient.Ingredient', verbose_name='Ингредиенты')),
            ],
        ),
    ]
