version: '3'
services:
    server:
        build:
            context: ./
            dockerfile: ./server/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./server:/server
        ports:
            - 8000:8000
        depends_on:
            - db
            # Указываем зависимость
            - redis
        environment:
            DEBUG: 'True'
            DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
            BROKER_URL: 'amqp://user:password@rabbitmq:5672/my_vhost'
            # Вот тут непонятно. Надо уазать переменную, чтобы потом использовать ее в settings.py, но где и как?
            REDIS_HOST: redis

    db:
        image: postgres:11.2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres

    # Тут определяем редис, вроде всё ок.
    redis:
        image: redis
        ports:
            - 6379:6379
