# Generated by Django 3.0.8 on 2020-07-24 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография')),
                ('open', models.TimeField(verbose_name='Открытие')),
                ('close', models.TimeField(verbose_name='Закрытие')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('avg_cost', models.FloatField(verbose_name='Средняя стоимость блюда')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заведение',
                'verbose_name_plural': 'Заведение',
                'ordering': ['id'],
            },
        ),
    ]
