# Generated by Django 3.0.8 on 2020-07-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='avg_cost',
            field=models.FloatField(default=0.0, verbose_name='Средняя стоимость блюда'),
        ),
    ]
