# Generated by Django 3.0.8 on 2020-07-27 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_auto_20200726_1207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catering',
            options={'ordering': ('id',), 'verbose_name': 'Заведение', 'verbose_name_plural': 'Заведение'},
        ),
        migrations.RenameField(
            model_name='catering',
            old_name='close',
            new_name='close_time',
        ),
        migrations.RenameField(
            model_name='catering',
            old_name='open',
            new_name='open_time',
        ),
    ]
